version: '3'

volumes:
    persistence:

services:
  workspace:
    build: ./build
    image: jtmotox/docker-workspace
    container_name: docker-workspace
    hostname: dw-${HOSTNAME}
    restart: always
    env_file: .env
    network_mode: host
    privileged: true
    ports:
      - "4445:4445"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - persistence:/persistence
      # CODE-SERVER MAC
      - "$HOME/Library/Application Support/Code/User:/home/dw/.local/share/code-server/User"
      - "$HOME/.vscode/extensions:/home/dw/.local/share/code-server/extensions"
